name: Build and Publish Docker image(s)

jobs:
  publish_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          platform: ${{ matrix.platforms }}
        with:
          context: ./${platform}/
          push: true
          tags: oscarotero/lume:1.3.0-${platform} # TODO: Parameterize version once this is finally working
    strategy:
      matrix:
        platforms:
          - alpine
          - debian

on:
  push:
    branches:
      - main
